apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: arc
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://actions-runner-controller.github.io/actions-runner-controller
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: arc
  namespace: flux-system
spec:
  targetNamespace: actions-runner-system
  releaseName: arc
  interval: 60m
  chart:
    spec:
      chart: actions-runner-controller/actions-runner-controller

      interval: 5m # scan the Helm repository every five minutes
      sourceRef:
        kind: HelmRepository
        name: arc
        namespace: flux-system
  test:
    enable: true # run tests on upgrades
