# apiVersion: v1
# kind: Namespace
# metadata:
#   name: action-runners
# ---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: test-runners
  namespace: action-runners
spec:
  replicas: 1
  template:
    spec:
      repository: heyrun/gitops 
      labels:
        - test-runner
      env:
      - name: RUNNER_FEATURE_FLAG_EPHEMERAL
        value: "true"
